version: '3'
services:
  app:
    image: hospital-prescription-api
    ports:
      - "9094:9094"
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prescriptions_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge